version: '3'

services:
  controller:
    container_name: english-controller
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env/env-controller
    restart: always
    ports:
      - 3030:3000
    volumes:
      - .:/srv/controller
    depends_on:
      - database

  database:
    container_name: english-postgres
    image: postgres:12
    env_file:
      - .env/env-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data
