default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rayenglish_development

test:
  <<: *default
  database: rayenglish_test

production:
  <<: *default
  database: deploy_production
  username: deploy
  password: '1-14-40ernazar'
